#!/usr/bin/env bash
# script that insta;;s Nginx and configure it
sudo apt-get -y update
sudo apt-get -y install nginx
#change the default nginx index.html to display a string
chown -R $ubuntu:$ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
