#!/usr/bin/env bash
# script that insta;;s Nginx and configure it
apt-get -y update
apt-get -y install nginx
chown -R $ubuntu:$ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart