#!/usr/bin/env bash
# Install and congigure Haproxy
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy
config_file=/etc/haproxy/haproxy.cfg
echo -e "listen 1959-lb-01
	bind *:80
	stats enable
	balance roundrobin
	server 1122-web-01 34.138.112.255:80 check
	server 1122-web-02 3.238.112.185:80 check" >> $config_file
sudo service haproxy restart
