#!/usr/bin/env bash
# Install and congigure Haproxy
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy
service haproxy start
echo -e "listen 1959-lb-01\n\tbind *:80\n\tstats enable\n\tbalance roundrobin\n\tserver 1959-web-01 34.138.112.255 check\n\tserver 1959-web-02 3.238.112.185 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
